export const environment = {
  production: false,
  CI: false,
  accessToken: 'access_token',
  refreshToken: 'refresh_token',
  pendingComments: 'pending_comments',
  storeLikes: 'likes',
  baseUrl: 'https://new.rent-home.uz',
  urls: {
    GET_ANNONCEMENTS: '/api/announcement/',
    POST_REGISTER: '/register/',
    POST_CODE: '/verification/code',
    POST_NUMBER: '/verification/number',
    POST_LOGIN: '/api/token/',
    GET_TRANSPORTS: '/api/transport/',
    GET_COMMENTS: '/api/comment/',
    POST_LOCATIONBUSES: '/api/buses/',
    POST_BUSROUTES: '/api/bus/',
    GET_GENDERS: '/api/lessee-types/',
    GET_REGIONS: '/api/regions/',
    GET_MIN_MAX_PRICE: '/api/max-and-min-price/announcement',
    GET_HOME_RECOMMENDATIONS: '/api/home/recommendations/'
  },
  authUrls: {
    POST_ANNONCEMENTS: '/api/announcement/',
    POST_ANNONCEMENT_STATUS: '/api/status-update/announcement',
    PUT_ANNONCEMENTS: '/api/announcement/',
    GET_MY_ANNONCEMENTS: '/api/my-announcement/',
    GET_ME: '/api/users/me/',
    GET_LIKES: '/api/like/',
    POST_LIKES: '/api/like/',
    DELETE_LIKES: '/api/like',
    POST_ALLTRANSPORTS: '/api/transport/',
    POST_TRANSPORTS: '/api/proxy/',
    POST_COMMENTS: '/api/comment/',
    DELETE_COMMENTS: '/api/comment/',
    PUT_USER: '/api/users/',
    GET_USERROOMS: '/api/user-rooms/',
    GET_USERMESSAGES: '/api/user-rooms/',
  },
};
